# Creates a release and pushes jar file to 
# https://github.com/TameU/tameu.github.io
#
# Triggered by:
# Push to stable with tags
#

on:
  push:
    branches: ["stable"]
    tags: ["v*"]

name: Create Full Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Zip artifact
        run: |
          cd lwjgl3/build
          ls -la
          zip -r UniverCity-${{ github.ref_name }}.zip libs

      - name: Upload zip
        uses: actions/upload-artifact@v4
        id: upload-zip
        with:
          name: UniverCity-${{ github.ref_name }}.zip
          path: lwjgl3/build/UniverCity-${{ github.ref_name }}.zip

      - name: Create release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # provided by actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Add release Asset
        id: upload_release_asses
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: lwjgl3/build/UniverCity-${{ github.ref_name }}.zip
          asset_name: UniverCity-${{ github.ref_name }}.zip
          asset_content_type: application/zip
  
  deploy:
    name: Deploy build
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'TameU/TameU.github.io'
          ref: 'main'
          token: ${{ secrets.PAGES_REPO_TOKEN }}

      - name: Setpu git config
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "<EMAIL>"
      
          
      - name: Download zip
        uses: actions/download-artifact@v4
        with:
          name: UniverCity-${{ github.ref_name }}.zip
      
      - name: Unzip
        run : |
          rm -r .bin
          unzip UniverCity-${{ github.ref_name }}.zip -d .bin
          cd .bin/libs
          mv * ..

      - name: Commit and push zip
        run: |
          export COMMIT_MESSAGE="Generated Release archive from ${{ github.repository }}/${{ github.ref }}@${{ github.sha }}"
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push